const DEFAULTS={lowRam:true,suspendMinutes:5,keepPinned:true,keepAudio:true,updateChecks:true};
function validTab(t){return t&&t.id&&t.url&&/^https?:/.test(t.url)}
async function optimizeTabs(){const s=await chrome.storage.local.get(DEFAULTS);if(!s.lowRam)return;const tabs=await chrome.tabs.query({});const now=Date.now(),limit=Math.max(1,s.suspendMinutes)*60000;for(const t of tabs){if(!validTab(t)||t.active||t.discarded)continue;if(s.keepPinned&&t.pinned)continue;if(s.keepAudio&&(t.audible||t.mutedInfo?.muted))continue;if(t.lastAccessed&&now-t.lastAccessed<limit)continue;try{await chrome.tabs.discard(t.id)}catch{}}}
async function checkUpdate(forceStartup=false){const s=await chrome.storage.local.get(DEFAULTS);if(!s.updateChecks)return;try{const r=await fetch('https://api.github.com/repos/louisoff84/ChromeFiltrer/releases/latest',{cache:'no-store'});if(!r.ok)return;const d=await r.json();const latest=String(d.tag_name||'').replace(/^v/,'');const current=chrome.runtime.getManifest().version;if(latest&&latest!==current){const k='updateShown_'+latest;const x=await chrome.storage.local.get(k);await chrome.storage.local.set({pendingUpdate:{version:latest,url:d.html_url,checkedAt:Date.now()}});if(forceStartup||!x[k]){await chrome.storage.local.set({[k]:true});chrome.tabs.create({url:chrome.runtime.getURL('update.html')})}}else{await chrome.storage.local.remove('pendingUpdate')}}catch{}}
function setupAlarms(){chrome.alarms.create('optimize',{periodInMinutes:1});chrome.alarms.create('updates',{periodInMinutes:360})}
chrome.runtime.onInstalled.addListener(async details=>{chrome.contextMenus.removeAll(()=>{chrome.contextMenus.create({id:'cf-open',title:'Ouvrir ChromeFiltrer',contexts:['all']});chrome.contextMenus.create({id:'cf-optimize',title:'Optimiser les onglets maintenant',contexts:['all']})});await chrome.storage.local.set({lastInstalledVersion:chrome.runtime.getManifest().version});if(details.reason==='update')chrome.tabs.create({url:chrome.runtime.getURL('update.html')});setupAlarms();checkUpdate(false)});
chrome.runtime.onStartup.addListener(async()=>{setupAlarms();await checkUpdate(true);await optimizeTabs()});
chrome.alarms.onAlarm.addListener(a=>{if(a.name==='optimize')optimizeTabs();if(a.name==='updates')checkUpdate(false)});
chrome.contextMenus.onClicked.addListener(i=>{if(i.menuItemId==='cf-open')chrome.runtime.openOptionsPage();if(i.menuItemId==='cf-optimize')optimizeTabs()});
chrome.runtime.onMessage.addListener(m=>{if(m?.type==='CF_BLOCKED'&&m.host)chrome.storage.local.get({totalBlocked:0,siteStats:{}},s=>{s.totalBlocked=(s.totalBlocked||0)+m.count;s.siteStats=s.siteStats||{};s.siteStats[m.host]=(s.siteStats[m.host]||0)+m.count;chrome.storage.local.set(s)});if(m?.type==='CF_OPTIMIZE')optimizeTabs()});