const SYNC_DEFAULTS={enabled:true,hideAds:true,hidePopups:true,hideCookieBanners:false,hideSponsoredText:true,blockedWords:[],customSelectors:[],whitelist:[],lowRam:true,reduceMotion:true,stopAutoplay:true,limitHeavyMedia:true};
const LOCAL_DEFAULTS={suspendMinutes:5,keepPinned:true,keepAudio:true,updateChecks:true,totalBlocked:0,siteStats:{}};
const $=id=>document.getElementById(id);const lines=v=>v.split('\n').map(x=>x.trim()).filter(Boolean);let syncCfg={},localCfg={};
function toast(msg){const t=$('toast');t.textContent=msg;t.style.opacity='1';setTimeout(()=>t.style.opacity='0',1400)}
function setting(container,key,label,value,onchange){const row=document.createElement('label');row.className='setting';const span=document.createElement('span');span.textContent=label;const cb=document.createElement('input');cb.type='checkbox';cb.checked=!!value;cb.addEventListener('change',()=>onchange(key,cb.checked));row.append(span,cb);container.append(row)}
async function load(){syncCfg=await chrome.storage.sync.get(SYNC_DEFAULTS);localCfg=await chrome.storage.local.get(LOCAL_DEFAULTS);render()}
async function render(){
 $('global').textContent=syncCfg.enabled?'Protection : ON':'Protection : OFF';$('statusText').textContent=syncCfg.enabled?'Protection active':'Protection désactivée';
 $('total').textContent=localCfg.totalBlocked||0;$('blockedWords').value=(syncCfg.blockedWords||[]).join('\n');$('customSelectors').value=(syncCfg.customSelectors||[]).join('\n');$('whitelist').value=(syncCfg.whitelist||[]).join('\n');$('suspendMinutes').value=String(localCfg.suspendMinutes||5);
 const tabs=await chrome.tabs.query({});$('discarded').textContent=tabs.filter(t=>t.discarded).length;
 const rs=$('ramSettings');rs.innerHTML='';[['lowRam','Activer RAM Saver'],['keepPinned','Ne jamais suspendre les onglets épinglés'],['keepAudio','Ne jamais suspendre les onglets audio'],['updateChecks','Vérifier les mises à jour au lancement']].forEach(([k,l])=>setting(rs,k,l,k in syncCfg?syncCfg[k]:localCfg[k],async(key,val)=>{if(key==='lowRam'){syncCfg[key]=val;await chrome.storage.sync.set({[key]:val})}else{localCfg[key]=val;await chrome.storage.local.set({[key]:val})}toast('Enregistré')}));
 const fs=$('filterSettings');fs.innerHTML='';[['hideAds','Bloquer les publicités'],['hidePopups','Bloquer les popups'],['hideCookieBanners','Masquer les bannières cookies'],['hideSponsoredText','Masquer le contenu sponsorisé'],['reduceMotion','Réduire les animations'],['stopAutoplay','Bloquer l’autoplay'],['limitHeavyMedia','Alléger images et iframes']].forEach(([k,l])=>setting(fs,k,l,syncCfg[k],async(key,val)=>{syncCfg[key]=val;await chrome.storage.sync.set({[key]:val});toast('Enregistré')}));
 const arr=Object.entries(localCfg.siteStats||{}).sort((a,b)=>b[1]-a[1]);$('topSites').innerHTML=arr.slice(0,8).map(([h,n])=>`<div><span>${h}</span><b>${n}</b></div>`).join('')||'<p>Aucune donnée.</p>';
 $('profileName').textContent=(localCfg.suspendMinutes||5)<=2?'4 Go':(localCfg.suspendMinutes||5)<=5?'8 Go':'Normal';diag();
}
async function diag(){const tabs=await chrome.tabs.query({});$('diag').textContent=JSON.stringify({version:chrome.runtime.getManifest().version,protection:syncCfg.enabled,ramSaver:syncCfg.lowRam,suspendMinutes:localCfg.suspendMinutes,tabs:tabs.length,discarded:tabs.filter(t=>t.discarded).length,blocked:localCfg.totalBlocked||0,lastUpdateCheck:localCfg.lastUpdateCheck||null},null,2)}
document.querySelectorAll('nav button').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.page').forEach(p=>p.classList.add('hidden'));$(b.dataset.page).classList.remove('hidden');$('pageTitle').textContent=b.textContent}));
$('global').onclick=async()=>{syncCfg.enabled=!syncCfg.enabled;await chrome.storage.sync.set({enabled:syncCfg.enabled});render()};
$('optimizeNow').onclick=()=>{chrome.runtime.sendMessage({type:'CF_OPTIMIZE'});toast('Optimisation lancée');setTimeout(load,700)};
$('saveRam').onclick=async()=>{localCfg.suspendMinutes=Number($('suspendMinutes').value)||5;await chrome.storage.local.set({suspendMinutes:localCfg.suspendMinutes});toast('RAM Saver enregistré');render()};
$('saveFilters').onclick=async()=>{syncCfg.blockedWords=lines($('blockedWords').value);syncCfg.customSelectors=lines($('customSelectors').value);await chrome.storage.sync.set({blockedWords:syncCfg.blockedWords,customSelectors:syncCfg.customSelectors});toast('Filtres enregistrés')};
$('saveSites').onclick=async()=>{syncCfg.whitelist=lines($('whitelist').value);await chrome.storage.sync.set({whitelist:syncCfg.whitelist});toast('Sites enregistrés')};
document.querySelectorAll('[data-profile]').forEach(b=>b.onclick=async()=>{const p=b.dataset.profile;const conf=p==='4gb'?{suspendMinutes:2,lowRam:true,reduceMotion:true,stopAutoplay:true,limitHeavyMedia:true,hideAds:true,hidePopups:true}:p==='8gb'?{suspendMinutes:5,lowRam:true,reduceMotion:true,stopAutoplay:true,limitHeavyMedia:true,hideAds:true,hidePopups:true}:{suspendMinutes:15,lowRam:false,reduceMotion:false,stopAutoplay:false,limitHeavyMedia:false,hideAds:true,hidePopups:true};const {suspendMinutes,...syncPart}=conf;await chrome.storage.local.set({suspendMinutes});await chrome.storage.sync.set(syncPart);toast('Profil appliqué');load()});
$('export').onclick=async()=>{const s=await chrome.storage.sync.get(null),l=await chrome.storage.local.get(null),blob=new Blob([JSON.stringify({sync:s,local:l},null,2)],{type:'application/json'}),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download='chromefiltrer-backup.json';a.click();URL.revokeObjectURL(u)};
$('import').onclick=async()=>{try{const d=JSON.parse($('importData').value);if(d.sync)await chrome.storage.sync.set(d.sync);if(d.local)await chrome.storage.local.set(d.local);toast('Sauvegarde importée');load()}catch{toast('JSON invalide')}};
$('reset').onclick=async()=>{await chrome.storage.sync.clear();await chrome.storage.local.clear();toast('Réinitialisé');load()};$('refreshDiag').onclick=diag;load();